### ISSUE TITLE
Api 키 가리셔야 해요...!

### ISSUE THREAD

**Issue by Yoochanhong** [kimwlsgh33/beco#1]
firebase 연동하고 만들어진 파일들은 이그노어 처리해주시고,, main에 들어있는 정보들도 환경변수로 따로 빼두시는게 좋을것 같아요

**Comment by kimwlsgh33** [comment]
> firebase 연동하고 만들어진 파일들은 이그노어 처리해주시고,, main에 들어있는 정보들도 환경변수로 따로 빼두시는게 좋을것 같아요

감시합니다 😊
